services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME:-boutique_db}
      POSTGRES_USER: ${DB_USER:-boutique_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-boutique_password}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-boutique_user} -d ${DB_NAME:-boutique_db}"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    volumes:
      - ./social_media:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SECRET_KEY=${SECRET_KEY:-django-insecure-your-secret-key}
      - DEBUG=${DEBUG:-1}
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-boutique_db}
      - DB_USER=${DB_USER:-boutique_user}
      - DB_PASSWORD=${DB_PASSWORD:-boutique_password}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin123}

volumes:
  postgres_data: